version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: motion-food
      POSTGRES_PASSWORD: motion
      POSTGRES_DB: motion-food
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer_motion
    restart: always
    ports:
      - "8082:8080"

volumes:
  postgres_data:
